### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by bartdorsey** [arkaneshiro/Sound-Zone#1]
# Feature List

This looks really well thought out! I don't see anything that jumps out at me that you should change.

# Front end routes

This also looks well thought out.

# backend routes

Typically the pattern for getting a user's sounds would be `/users/:id/sounds` not `sounds/user/:id`
I'm confused a little bit about getting all the users sounds vs getting a users feed? What's the difference?

On the social links, /social isn't a great URL pattern. you should think about URLs being about "Resources", so for instance to add a like to a sound, it would be a POST to `/sounds/:id/likes` 

So I would rework your backend URLs to follow the normal resource pattern. 

# Schema

Why "hostId" instead of just "userId" in the sounds table?

Can a sound be assigned to multiple genres? I see you have a many-to-many relationship for them, unsure if that was intentional or not. 

Other than those nit picks it looks great.

**Comment by arkaneshiro** [comment]
# backend routes

Great points here about naming routes, my initial intention was just to add more separation for the routes other than just 'users' or 'sounds' so that eventually when I'm working on these I could make smaller files with less routes per file for easier management, but I think what you're saying makes sense.

The difference between a users sounds and a users feed is that the feed not only includes sounds uploaded by the user, but sounds uploaded by users that they follow. 

# Schema

Great point about the 'userId' vs 'hostId' naming, this is an ez fix.

Sounds can be assigned multiple genres, yes! I thought it would make it more interesting for users who are uploading sounds, and eventually if im able to get to it, for searching sounds.
